import 'dart:convert';

class IngredientList {
  List<String> _fullIngredientList = <String>[
    'Sugar',
    'Salt',
    'Water',
    'Oil',
    'Cereal',
    'Flour',
    'Milk',
    'Cocoa',
    'Onion',
    'Egg',
    'Garlic',
    'Tomato',
    'Pepper',
    'Cocoa butter',
    'Vinegar',
    'Meat',
    'Rice',
    'Cream',
    'Pork',
    'Lemon juice',
    'Sea salt',
    'Corn',
    'Cocoa powder',
    'Carrot',
    'Butter',
    'Palm oil',
    'Apple',
    'Chocolate',
    'Cheese',
    'Apples',
    'Asparagus',
    'Bananas',
    'Beans',
    'Beef',
    'Beets',
    'Bell Peppers',
    'Blueberries',
    'Broccoli',
    'Brussels Sprouts',
    'Cabbage',
    'Cane Berries',
    'Carrots',
    'Cauliflower',
    'Celery',
    'Cheese',
    'Cherries',
    'Chicken',
    'Corn',
    'Cranberries',
    'Cucumber',
    'Eggplant',
    'Eggs',
    'Garlic',
    'Grapes',
    'Green Beans',
    'Hot Peppers',
    'Kale',
    'Kiwi',
    'Leafy Greens',
    'Leeks',
    'Lentils',
    'Mangos',
    'Microgreens',
    'Milk',
    'Mushrooms',
    'Oats',
    'Onions',
    'Oranges',
    'Parsnips',
    'Peaches',
    'Pears',
    'Peas',
    'Pineapple',
    'Pork',
    'Potatoes',
    'Pumpkin',
    'Radishes',
    'Rhubarb',
    'Rice',
    'Salad Greens',
    'Salmon',
    'Spinach',
    'Split Peas',
    'Strawberries',
    'Summer Squash',
    'Sweet Potato',
    'Tofu',
    'Tomatoes',
    'Tuna',
    'Turkey',
    'Turnips',
    'Water',
    'Watermelon',
    'Wheat',
    'Whole Grains',
    'Winter Squash',
    'Yogurt'
  ];

  List<String> getIngredientList(){
    return _fullIngredientList;
  }
 }